// app/layout.js (or _app.js)
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// Import Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Only load the weights you need
  variable: "--font-montserrat",
  display: "swap",
});

// Keep your metadata
export const metadata = {
  title: "G.D College of Education",
  description: "Generated by create next app",
  icons: { icon: "/logo1.svg"}
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-sans antialiased bg-cover bg-center`}
        style={{ backgroundImage: "url('/bg.png')" }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
